# Generated by Django 2.2.1 on 2020-07-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='curp',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
