# Generated by Django 2.2.1 on 2020-07-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0002_auto_20200703_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
